# Generated by Django 4.2.11 on 2024-03-17 18:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aeroplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aeroplane_id', models.CharField(max_length=255, unique=True)),
                ('aeroplane_name', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_name', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_id', models.CharField(max_length=255, unique=True)),
                ('starting_time', models.DateTimeField()),
                ('reach_time', models.DateTimeField()),
                ('price', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aeroplane', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='airport.aeroplane')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_airport', to='airport.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'Super Admin'), (2, 'Admin'), (3, 'Airline Staff'), (4, 'Airport Staff'), (5, 'Security Staff'), (6, 'Passenger')], primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, choices=[(1, 'Super Admin'), (2, 'Admin'), (3, 'Airline Staff'), (4, 'Airport Staff'), (5, 'Security Staff'), (6, 'Passenger')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('contact', models.BigIntegerField(db_index=True, default=0)),
                ('username', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('last_attempt', models.DateTimeField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('by_bulk', models.BooleanField(default=False)),
                ('employee_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('adhar_no', models.CharField(max_length=255, unique=True)),
                ('salary', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='UserRoleMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='airport.aeroplane')),
                ('airport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='airport.airport')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='air_group_user', to='airport.user')),
            ],
        ),
        migrations.CreateModel(
            name='TicketCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=255, unique=True)),
                ('seat_no', models.IntegerField(blank=True, null=True)),
                ('is_booked', models.BooleanField(default=False)),
                ('is_checked', models.BooleanField(default=False)),
                ('is_security_checked', models.BooleanField(default=False)),
                ('is_boarded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_tckt', to='airport.airport')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='airport.flight')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='airport.user')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_tckt', to='airport.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Runway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runway_number', models.IntegerField()),
                ('is_occupied', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='airport.airport')),
            ],
        ),
        migrations.CreateModel(
            name='NoticeBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arraival_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('departure_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='airport.flight')),
            ],
        ),
        migrations.CreateModel(
            name='LuggageCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('luggage_id', models.CharField(max_length=255, unique=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('no_of_luggage', models.IntegerField(blank=True, null=True)),
                ('is_checked', models.BooleanField(default=False)),
                ('is_boarded', models.BooleanField(default=False)),
                ('is_security_checked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='airport.flight')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='airport.ticketcounter')),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='runway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='airport.runway'),
        ),
        migrations.AddField(
            model_name='flight',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_airport', to='airport.airport'),
        ),
    ]
