# Generated by Django 4.2.11 on 2024-03-18 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0002_alter_role_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airport',
            options={'ordering': ['-created_at']},
        ),
    ]
